name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  publish-update:
    name: Publish EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "EXPO_TOKEN GitHub Actions secret is required."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Link EAS project
        run: eas init --account mun_ta_sir --non-interactive

      - name: Publish update to preview channel
        run: eas update --channel preview --message "GitHub commit ${{ github.sha }}" --non-interactive
